// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiPractice.Data;

#nullable disable

namespace WebApiPractice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241218040156_FluentApi")]
    partial class FluentApi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WebApiPractice.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("StateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CityId");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            Name = "Los Angeles",
                            StateId = 1
                        },
                        new
                        {
                            CityId = 2,
                            Name = "San Francisco",
                            StateId = 1
                        },
                        new
                        {
                            CityId = 3,
                            Name = "Houston",
                            StateId = 2
                        },
                        new
                        {
                            CityId = 4,
                            Name = "Dallas",
                            StateId = 2
                        },
                        new
                        {
                            CityId = 5,
                            Name = "Vancouver",
                            StateId = 3
                        },
                        new
                        {
                            CityId = 6,
                            Name = "Toronto",
                            StateId = 4
                        },
                        new
                        {
                            CityId = 7,
                            Name = "London",
                            StateId = 5
                        },
                        new
                        {
                            CityId = 8,
                            Name = "Mumbai",
                            StateId = 6
                        },
                        new
                        {
                            CityId = 9,
                            Name = "Pune",
                            StateId = 6
                        });
                });

            modelBuilder.Entity("WebApiPractice.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "India"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "United States"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "Canada"
                        },
                        new
                        {
                            CountryId = 4,
                            Name = "United Kingdom"
                        });
                });

            modelBuilder.Entity("WebApiPractice.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Name = "Laptop",
                            Price = 750.00m,
                            Stock = 20
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Name = "Smartphone",
                            Price = 500.00m,
                            Stock = 50
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Name = "Headphones",
                            Price = 100.00m,
                            Stock = 100
                        });
                });

            modelBuilder.Entity("WebApiPractice.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("StateId");

                    b.HasIndex("CountryId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            CountryId = 2,
                            Name = "California"
                        },
                        new
                        {
                            StateId = 2,
                            CountryId = 2,
                            Name = "Texas"
                        },
                        new
                        {
                            StateId = 3,
                            CountryId = 3,
                            Name = "British Columbia"
                        },
                        new
                        {
                            StateId = 4,
                            CountryId = 3,
                            Name = "Ontario"
                        },
                        new
                        {
                            StateId = 5,
                            CountryId = 4,
                            Name = "England"
                        },
                        new
                        {
                            StateId = 6,
                            CountryId = 1,
                            Name = "Maharashtra"
                        },
                        new
                        {
                            StateId = 7,
                            CountryId = 1,
                            Name = "Delhi"
                        });
                });

            modelBuilder.Entity("WebApiPractice.Models.City", b =>
                {
                    b.HasOne("WebApiPractice.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("WebApiPractice.Models.State", b =>
                {
                    b.HasOne("WebApiPractice.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WebApiPractice.Models.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("WebApiPractice.Models.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
