// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiPractice.Data;

#nullable disable

namespace WebApiPractice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241217093906_Caching")]
    partial class Caching
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WebApiPractice.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("StateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CityId");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            Name = "Los Angeles",
                            StateId = 1
                        },
                        new
                        {
                            CityId = 2,
                            Name = "San Francisco",
                            StateId = 1
                        },
                        new
                        {
                            CityId = 3,
                            Name = "Houston",
                            StateId = 2
                        },
                        new
                        {
                            CityId = 4,
                            Name = "Dallas",
                            StateId = 2
                        },
                        new
                        {
                            CityId = 5,
                            Name = "Vancouver",
                            StateId = 3
                        },
                        new
                        {
                            CityId = 6,
                            Name = "Toronto",
                            StateId = 4
                        },
                        new
                        {
                            CityId = 7,
                            Name = "London",
                            StateId = 5
                        },
                        new
                        {
                            CityId = 8,
                            Name = "Mumbai",
                            StateId = 6
                        },
                        new
                        {
                            CityId = 9,
                            Name = "Pune",
                            StateId = 6
                        });
                });

            modelBuilder.Entity("WebApiPractice.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "India"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "United States"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "Canada"
                        },
                        new
                        {
                            CountryId = 4,
                            Name = "United Kingdom"
                        });
                });

            modelBuilder.Entity("WebApiPractice.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SupplierCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupplierInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Description = "High-end gaming laptop",
                            IsAvailable = true,
                            Name = "Laptop",
                            Price = 1500.99m,
                            StockQuantity = 50,
                            SupplierCost = 1200.00m,
                            SupplierInfo = "Tech Supplier Co."
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Description = "Latest model with advanced features",
                            IsAvailable = true,
                            Name = "Smartphone",
                            Price = 999.99m,
                            StockQuantity = 100,
                            SupplierCost = 750.00m,
                            SupplierInfo = "Mobile Solutions Inc."
                        },
                        new
                        {
                            Id = 3,
                            Category = "Furniture",
                            Description = "Ergonomic office chair",
                            IsAvailable = true,
                            Name = "Desk Chair",
                            Price = 299.99m,
                            StockQuantity = 25,
                            SupplierCost = 200.00m,
                            SupplierInfo = "Furniture Plus Ltd."
                        });
                });

            modelBuilder.Entity("WebApiPractice.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("StateId");

                    b.HasIndex("CountryId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            CountryId = 2,
                            Name = "California"
                        },
                        new
                        {
                            StateId = 2,
                            CountryId = 2,
                            Name = "Texas"
                        },
                        new
                        {
                            StateId = 3,
                            CountryId = 3,
                            Name = "British Columbia"
                        },
                        new
                        {
                            StateId = 4,
                            CountryId = 3,
                            Name = "Ontario"
                        },
                        new
                        {
                            StateId = 5,
                            CountryId = 4,
                            Name = "England"
                        },
                        new
                        {
                            StateId = 6,
                            CountryId = 1,
                            Name = "Maharashtra"
                        },
                        new
                        {
                            StateId = 7,
                            CountryId = 1,
                            Name = "Delhi"
                        });
                });

            modelBuilder.Entity("WebApiPractice.Models.City", b =>
                {
                    b.HasOne("WebApiPractice.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("WebApiPractice.Models.State", b =>
                {
                    b.HasOne("WebApiPractice.Models.Country", "Country")
                        .WithMany("States")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WebApiPractice.Models.Country", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("WebApiPractice.Models.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
