// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiPractice.Data;

#nullable disable

namespace WebApiPractice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WebApiPractice.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SupplierCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupplierInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Description = "High-end gaming laptop",
                            IsAvailable = true,
                            Name = "Laptop",
                            Price = 1500.99m,
                            StockQuantity = 50,
                            SupplierCost = 1200.00m,
                            SupplierInfo = "Tech Supplier Co."
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            Description = "Latest model with advanced features",
                            IsAvailable = true,
                            Name = "Smartphone",
                            Price = 999.99m,
                            StockQuantity = 100,
                            SupplierCost = 750.00m,
                            SupplierInfo = "Mobile Solutions Inc."
                        },
                        new
                        {
                            Id = 3,
                            Category = "Furniture",
                            Description = "Ergonomic office chair",
                            IsAvailable = true,
                            Name = "Desk Chair",
                            Price = 299.99m,
                            StockQuantity = 25,
                            SupplierCost = 200.00m,
                            SupplierInfo = "Furniture Plus Ltd."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
